*
!install.sh
!tests/apope_sample.txt
!tests/apope_sample_*.wav
!tests/samples_match.py
!voices/
!wheels/
!debian/control.in.*

!setup.py
!LICENSE
!MANIFEST.in
!README.md
!requirements.txt

# opentts-abc
!opentts_abc/*.py
!opentts_abc/VERSION
!opentts_abc/py.typed

# Mimic 3 TTS
!mimic3_tts/*.py
!mimic3_tts/voices.json
!mimic3_tts/VERSION
!mimic3_tts/py.typed

# HTTP server
!mimic3_http/css/
!mimic3_http/img/
!mimic3_http/templates/
!mimic3_http/*.py
!mimic3_http/VERSION
!mimic3_http/py.typed
